### ISSUE TITLE
Issue: Command List

### ISSUE THREAD

**Issue by glitchninja2000** [laconalabs/elliptical#11]
It would be nice to have a list of all the commands.
I'd be willing to create all the Wiki pages if the was a list.
I'll start with the ones on the [hompage](http://www.lacona.io/) for now, but a please send me a list.

**Comment by brandonhorst** [comment]
Hey - thanks so much for doing this. But if possible, could you please do it on https://github.com/lacona/LaconaApp? `lacona/lacona

**Comment by black-snow** [comment]
Is there a list of all commands somewhere? It'd be quite a pita to go through the code to see what lacona is capable of. @brandonhorst

**Comment by brandonhorst** [comment]
If you're talking about [Lacona](https://github.com/laconalabs/LaconaApp/issues), then there currently is not. Could you submit an issue on that repo to add one to the App?

This repo is a general-purpose library that is used by Lacona, but is also used by other things.

**Comment by black-snow** [comment]
Sure thing
