### ISSUE TITLE
need bare-bone example

### ISSUE THREAD

**Issue by gasolin** [laconalabs/elliptical#9]
lacona looks cool but the [basic usage example](https://github.com/lacona/lacona#usage-example) seems need some react knowledge to execute the script.

First, the script need both lacona, lacona-parse, 
`npm install lacona lacona-parse`

then it need some tooling like (babel-cli, transform-react-jsx plugin) to execute the script
`npm install babel-cli transform-react-jsx`

Running command

```
babel --optional runtime --stage 0 --plugins transform-react-jsx  main.jsx > main.js
```

can translate jsx to dom-like syntax, but I still got error with lacona
 
```
<project folder>/node_modules/lacona/lib/parser.js:61
        throw _iteratorError;
        ^
Error
    at Object.<anonymous> (/home/gasolin/Document/laca/node_modules/lacona/lib/error.js:12:25)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/gasolin/Document/laca/node_modules/lacona/lib/descriptor.js:28:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

It will be helpful to setup a bare-bone example (or a sample repo), so people who is new to those tooling can try lacona with less burden.

**Comment by brandonhorst** [comment]
Yeah, I agree. I'll put a demo repo together today or tomorrow.

**Comment by bradvogel** [comment]
Here's an example using basic es5: https://gist.github.com/bradvogel/9759b3fe50828ad6bae8

**Comment by brandonhorst** [comment]
@bradvogel That's great, thanks! - I've added a link to the README. cc11bddf2660867f396d7311b7bdf16ab9216730

@gasolin I'm so sorry that I haven't got around to "today or tomorrow" yet - the Beta Launch has been keeping me busy. I still want to do this.

**Comment by gasolin** [comment]
@bradvogel thanks it works well.

Here's the dependency libraries need to execute the gist
```
{
  "name": "lacona_sample",
  "version": "1.0.0",
  "description": "sample",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-runtime": "^6.3.19",
    "lacona": "^0.37.0",
    "lacona-phrase": "^0.9.1",
    "lacona-phrase-datetime": "^0.7.1",
    "lacona-phrase-string": "^0.4.0",
    "underscore": "^1.8.3"
  }
}
```

**Comment by bradvogel** [comment]
Added, thanks!

**Comment by brandonhorst** [comment]
So by "today or tomorrow", I meant "3 and a half months from now". But it's here!

https://github.com/laconalabs/elliptical-example

**Comment by gasolin** [comment]
better late than never, thanks!
